source 'https://rubygems.org'

gem 'jekyll', '4.3.1'

group :jekyll_plugins do
  gem 'jekyll-archives', '2.2.1'
  gem 'jekyll-feed', '0.15.1'
  gem 'jekyll-paginate', '1.1.0'
  gem 'jekyll-seo-tag', '2.7.1'
  gem 'jekyll-sitemap', '1.4.0'
end

gem "kramdown", "~> 2.3"

gem "rouge", "~> 3.28"

gem "ffi", "~> 1.14.2 "

gem "tzinfo"

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

gem 'wdm', ">= 0.1.0"
